feat: nestJs第一次提交
opentiny/tiny-cli pull request #139
Opened 2024-07-02 11:24 UTC by Muyu-art

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-cli/blob/main/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-07-02 11:39 UTC, GaoNeng-wWw requested changes

2024-07-02 11:39 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/libs/db/src/db.module.ts
> +      autoLoadEntities: true,
这一段应该是允许用户配置

2024-07-02 11:39 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/app.module.ts
> +    //EmployeesModule,
```suggestion

```

2024-07-02 11:39 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/auth/auth.module.ts
> +        expiresIn: '2h',
该属性应该由配置文件配置

2024-07-02 11:39 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/auth/constant.ts
> +export const SECRET = 'secret';
这一段应该由配置文件配置

2024-07-02 11:39 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/permission/permission.guard.ts
> +    console.log(permissionNames);
```suggestion

```

2024-07-03 13:29 UTC, GaoNeng-wWw requested changes

2024-07-03 13:29 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/.env
这个文件最好是不要提交

2024-07-03 13:29 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/app.service.ts
如果这个文件用不到的话，可以直接删掉

2024-07-03 13:29 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/app.controller.ts
如果这个文件用不到的话，可以直接删掉

2024-07-03 13:29 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/auth/auth.controller.ts
> +  }
```suggestion
```

2024-07-03 13:29 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/auth/auth.module.ts
> +        },
```suggestion
        signOptions: {
          expiresIn: configService.get('EXPIRES_IN'),
        },
```
这里最好也是使用配置文件控制

2024-07-03 13:29 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/auth/constant.ts
这个文件可以直接删掉了, 不过要注意有没有引用

2024-07-03 13:29 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/package.json
> +    "pg": "^8.12.0",
项目似乎使用的是mysql数据库

2024-07-03 13:33 UTC, kagol commented
可以在PR描述里介绍下这个PR主要做了什么事情

2024-07-03 13:49 UTC, kagol reviewed
dto是什么单词的缩写呢？

2024-07-03 13:59 UTC, GaoNeng-wWw commented
> dto是什么单词的缩写呢？

Data transfer object (数据传输对象)

https://juejin.cn/post/7067347098441613343

2024-07-04 08:47 UTC, GaoNeng-wWw requested changes

2024-07-04 08:47 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/user/user.service.ts
> +      throw new HttpException('删除成功', HttpStatus.OK);
这里不应该抛出错误，而是直接返回文本

2024-07-04 08:47 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/user/user.service.ts
> +        throw new HttpException('密码修改成功', HttpStatus.OK);
这里不应该抛出次错误，而是应该返回文本

2024-07-04 13:12 UTC, GaoNeng-wWw requested changes

2024-07-04 13:12 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/auth/auth.service.ts
> +    console.log(email);
```suggestion

```

2024-07-04 13:12 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/auth/auth.service.ts
> +    });
这里不应该直接使用IoRedis，而是应该在AuthModule或AppModule中诸如一个Module，以便日后其他模块注入

2024-07-04 13:12 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/user/user.service.ts
> +      user.deleteAt = new Date(); // 设置软删除字段
```suggestion
      user.deleteAt = new Date().getTime();
```
这样写是不是语义更加明确，避免了隐式转换带来的维护心智负担

2024-07-04 13:12 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/auth/auth.service.ts
> +    );
1. 应该是使用注入的service
2. 过期时间如果可以最好是让配置文件来确定

2024-07-05 12:57 UTC, GaoNeng-wWw requested changes

2024-07-05 12:57 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/libs/redis/redis.service.ts
> +      port: 6379,
这里应该注入`ConfigService`来获取配置文件的配置项

2024-07-06 04:59 UTC, GaoNeng-wWw requested changes

2024-07-06 04:59 UTC, GaoNeng-wWw commented on packages/toolkits/pro/template/server/nestJs/src/auth/auth.service.ts
> +    }
如果用户不存在，这里会直接返回500错误。应该返回400或404，提示用户不存在

2024-07-07 12:38 UTC, GaoNeng-wWw approved these changes

2024-07-09 14:36 UTC, merged

2025-02-07 07:10 UTC, kagol commented
@all-contributors please add @Muyu-art for code.